name: DipSA Workshop workflow

on:
  push:
    branches:
    - 'v[0-9]+.[0-9]+' 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Echo the branch name
      run: echo "The current branch is ${{ github.ref_name }}"

    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}

    # Actions to deploy railway
    - name: Use Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    # Action to create release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false


