name: DipSA Workshop workflow
#test norun
on:
  push:
    branches:
    - 'v[0-9]+.[0-9]+' 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    # if commit message starts with #NORUN, stop pipeline
    if: ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}
    
    steps:
    - name: Echo the branch name
      run: echo "The current branch is ${{ github.ref_name }}"

    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    
    - name: Echo commit message
      run: echo "The commit message is ${{ github.event.head_commit.message }}"

    # Actions to deploy railway
    - name: Use Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    # Action to create release
    - name: Create Release
    - uses: ncipollo/release-action@v1
      with:
        commit: ${{ github.ref_name }}
        tag: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}


